# Generated by Django 5.2.13 on 2026-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='insurance_documents/')),
                ('document_type', models.CharField(choices=[('policy', 'Policy Document'), ('claim', 'Claim Document'), ('medical', 'Medical Record'), ('proposal', 'Proposal Form'), ('legal', 'Legal Document'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('coverage_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('exclusions', models.TextField(blank=True, null=True)),
                ('claim_terms', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
