# Generated by Django 5.2.13 on 2026-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedocument',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='predicted_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='smoker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
