# Generated by Django 6.0.4 on 2026-05-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_chatmessage_claimassessment_policydocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='reminder_sent_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='reminder_sent_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='reminder_sent_7',
            field=models.BooleanField(default=False),
        ),
    ]
