# Generated by Django 6.0.4 on 2026-05-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_policydocument_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='phone_number',
            field=models.CharField(blank=True, help_text='With country code, e.g. +919876543210', max_length=20),
        ),
    ]
